version: '3.8'

services:
  app:
    container_name: demo-toolbox-back-container
    image: node:14-alpine
    entrypoint: /bin/sh
    volumes:
      - .:/app
    tty: true
    ports:
      - "3005:3005"
    working_dir: /app
    env_file:
      - .env
